/**
 * AI Provider Wrapper - Auto-generated by Code Engine Agent
 * 
 * 统一接口封装，支持 OpenAI / Anthropic / 自定义 Provider
 */

export interface AIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface AIResponse {
  content: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export interface AIProvider {
  chat(messages: AIMessage[], options?: Record<string, any>): Promise<AIResponse>;
  stream?(messages: AIMessage[], options?: Record<string, any>): AsyncIterable<string>;
}

export class OpenAIProvider implements AIProvider {
  private apiKey: string;
  private baseURL: string;

  constructor(config: { apiKey: string; baseURL?: string }) {
    this.apiKey = config.apiKey;
    this.baseURL = config.baseURL || 'https://api.openai.com/v1';
  }

  async chat(messages: AIMessage[], options: Record<string, any> = {}): Promise<AIResponse> {
    const response = await fetch(`${this.baseURL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`
      },
      body: JSON.stringify({
        model: options.model || 'gpt-4',
        messages,
        temperature: options.temperature ?? 0.7,
        max_tokens: options.maxTokens || 4096
      })
    });

    if (!response.ok) {
      throw new Error(`AI API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json() as any;
    return {
      content: data.choices[0].message.content,
      usage: data.usage
    };
  }
}

export class AIClient {
  private provider: AIProvider;

  constructor(provider: AIProvider) {
    this.provider = provider;
  }

  async ask(prompt: string, systemPrompt?: string): Promise<string> {
    const messages: AIMessage[] = [];
    if (systemPrompt) {
      messages.push({ role: 'system', content: systemPrompt });
    }
    messages.push({ role: 'user', content: prompt });
    
    const response = await this.provider.chat(messages);
    return response.content;
  }

  async chat(messages: AIMessage[], options?: Record<string, any>): Promise<AIResponse> {
    return this.provider.chat(messages, options);
  }

  setProvider(provider: AIProvider) {
    this.provider = provider;
  }
}
